default: &default
  elevenlabs_turbo_v2_5_audio:
    adam:
      voice_id: hIssydxXZ1WuDorjx6Ic
    victoria:
      voice_id: qSeXEcewz7tA0Q0qk9fH
    knox:
      voice_id: cgLpYGyXZhkyalKZ0xeZ
    milo:
      voice_id: GUDYcgRAONiI1nXDcNQQ
    hope:
      voice_id: tnSpp4vdxKPjI9w0GnoV

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
