default: &default
  generate_image:
    mystic_image: 2
    flux_image: 1
    gemini_image: 1
    imagen_image: 1
  generate_video:
    kling_2_1_pro_image_to_video: 10
    seedance_1_5_pro_image_to_video: 6
  prompt:
    extend_prompt: 1

development:
  <<: *default

test:
  <<: *default
  generate_image:
    mystic_image: 2
    flux_image: 1
    gemini_image: 1
    imagen_image: 0
  generate_video:
    kling_2_1_pro_image_to_video: 10
    seedance_1_5_pro_image_to_video: 6
  prompt:
    extend_prompt: 1

production:
  <<: *default
