default: &default
  images:
    mystic_image: 2
    gemini_image: 1
    imagen_image: 1
  videos:
    kling_2_1_pro_image_to_video: 10

development:
  <<: *default

test:
  <<: *default
  images:
    mystic_image: 2
    gemini_image: 1
    imagen_image: 0

production:
  <<: *default
