default: &default
  generate_image:
    flux_image: 1
    nano_banana_image: 1
    imagen_image: 1
  edit_image:
    nano_banana_edit_image: 1
  generate_video:
    kling_2_1_pro_image_to_video: 10
    hailuo_02_standard_image_to_video: 6
    veo3_1_lite_image_to_video: 5
  generate_audio:
    elevenlabs_turbo_v2_5_audio: 1
  prompt:
    extend_prompt: 1

development:
  <<: *default

test:
  <<: *default
  generate_image:
    flux_image: 1
    nano_banana_image: 1
    imagen_image: 0
  edit_image:
    nano_banana_edit_image: 1
  generate_video:
    kling_2_1_pro_image_to_video: 10
    hailuo_02_standard_image_to_video: 6
    veo3_1_lite_image_to_video: 5
  generate_audio:
    elevenlabs_turbo_v2_5_audio: 1
  prompt:
    extend_prompt: 1

production:
  <<: *default
